apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-hello
  annotations:
    kubernetes.io/ingress.class: "nginx"   
spec:
  rules:
  - host: hello.k8s.thedutchmc.nl
    http:
      paths:
      - path: /hello
        backend:
          serviceName: web
          servicePort: 8080
