apiVersion: v1
kind: Secret
metadata:
  name: lidarr-iscsi-chap
  namespace: default
type: "kubernetes.io/iscsi-chap"
data:
  node.session.auth.username: "bGlkYXJyCg=="
  node.session.auth.password: "UFI2WGMyWHpzQjNISHk4clIycTkK"
---
#lidarrs storage directory. iSCSI
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-config-pv
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  iscsi:
    targetPortal: 192.168.2.2:3260
    iqn: 'iqn.2021-02.storage.thedutchmc.nl:lidarr'
    lun: 1
    fsType: 'ext4'
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: lidarr-iscsi-chap
  persistentVolumeReclaimPolicy: Retain
---
#Transmissions download directory. NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-lidarr-storage-pv
spec:
  capacity:
    storage: 2000G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-pool/VM/100/transmission
    server: 192.168.1.8
  persistentVolumeReclaimPolicy: Retain
---
#Export Directory for lidarr. NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-lidarr-storage-pv
spec:
  capacity:
    storage: 10000G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-pool/media/music
    server: 192.168.1.8
  persistentVolumeReclaimPolicy: Retain
---
#lidarrs config directory
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config-pvc
spec:
  volumeName: lidarr-config-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
---
#Transmissions download directory
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-lidarr-storage-pvc
spec:
  volumeName: transmission-lidarr-storage-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000G
---
#lidarrs export directory for TV Shows
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-lidarr-storage-pvc
spec:
  volumeName: music-lidarr-storage-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000G
---
#Deployment. lidarr container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr-deployment
  labels:
    app: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: linuxserver/lidarr
        ports:
        #Webinterface
        - containerPort: 8686
          name: webint
        volumeMounts:
        #lidarrs config directory (iSCSI)
        - name: lidarr-config
          mountPath: /config
        #Transmission download directory
        - name: transmission-storage
          mountPath: /data/completed/
        #Final resting place for the downloaded media
        - name: music-storage
          mountPath: /music
      volumes:
      - name: lidarr-config
        persistentVolumeClaim:
          claimName: lidarr-config-pvc
      - name: transmission-storage
        persistentVolumeClaim:
          claimName: transmission-lidarr-storage-pvc
      - name: music-storage
        persistentVolumeClaim: 
          claimName: music-lidarr-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr-service
spec:
  selector:
    app: lidarr
  ports:
  #Webinterface
  - protocol: TCP
    name: webint
    port: 8686
    targetPort: 8686
---
#Ingress resource. Picked up by the NGINX ingress controller
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: lidarr-ingress
  annotations:
    kubernets.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: 85.144.63.138,192.168.1.0/24
    nginx.ingress.kubernetes.io/proxy-body-size: 150m

spec:
  tls:
  - hosts:
    - lidarr.k8s.thedutchmc.nl
    secretName: thedutchmc-tls
  rules:
  - host: lidarr.k8s.thedutchmc.nl
    http:
      paths:
      - backend:
          serviceName: lidarr-service
          servicePort: 8686
