apiVersion: v1
kind: Secret
metadata:
  name: netherlandsbot-core-iscsi-chap
  namespace: default
type: "kubernetes.io/iscsi-chap"
data:
  node.session.auth.username: "bmV0aGVybGFuZHNib3QK"
  node.session.auth.password: "WkU3M240QndrWkhHU3UK"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: netherlandsbot-core-pv
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  iscsi:
    targetPortal: 192.168.2.4:3260
    iqn: 'iqn.2021-03.storage.thedutchmc.nl:netherlandsbot-core'
    lun: 1
    fsType: 'ext4'
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: netherlandsbot-core-iscsi-chap
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netherlandsbot-core-pvc
spec:
  volumeName: netherlandsbot-core-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netherlandsbot-core-deployment
  labels:
    app: netherlandsbot-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netherlandsbot-core
  template:
    metadata:
      labels:
        app: netherlandsbot-core
    spec:
      containers:
      - name: netherlandsbot-core
        image: registry.thedutchmc.nl/netherlandsbot-core:latest
        ports:
        - name: tcp-module
          containerPort: 5555
        volumeMounts:
        - name: config
          mountPath: /
        env:
        - name: "HOI_MODULE"
          value: "YES"
        - name: "DICK_MEASURING_CONTEST"
          value: "YES"
        - name: "TCP_MODULE"
          value: "YES"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: netherlandsbot-core-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: netherlandsbot-core-service
spec:
  type: LoadBalancer
  selector:
    app: netherlandsbot-core
  ports:
  - protocol: TCP
    name: tcp-module
    port: 5555
    targetPort: 5555
