apiVersion: v1
kind: ConfigMap
metadata:
  name: netherlandsbot-core-config
data:
  hoi-module: |
    channelId: 811307775396413481
    notHoiMessages:
    - "Moet jij eens goed luisteren stuk stront dat je bent. Wij staan hier alleen 'Hoi' toe!"
    - "Oi vieze tering lijer. Kun je niet lezen ofzo? Alleen 'Hoi' hier."
  tcp-module: |
    port: 5555
    healthCheckInterval: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netherlandsbot-core-deployment
  labels:
    app: netherlandsbot-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netherlandsbot-core
  template:
    metadata:
      labels:
        app: netherlandsbot-core
    spec:
      containers:
      - name: netherlandsbot-core
        image: registry.thedutchmc.nl/netherlandsbot-core:latest
        ports:
        - name: tcp-module
          containerPort: 5555
        volumeMounts:
        - name: config
          mountPath: /config
        - name: module-config
          mountPath: /moduleconfig/
        env:
        - name: "HOI_MODULE"
          value: "YES"
        - name: "DICK_MEASURING_CONTEST"
          value: "YES"
        - name: "TCP_MODULE"
          value: "NO"
      volumes:
      - name: config
        secret:
          secretName: netherlandsbot-core
          items:
          - key: config
            path: config.yml
      - name: module-config
        configMap:
          name: netherlandsbot-core-config
          items:
          - key: tcp-module
            path: TCPModule.yml
          - key: hoi-module
            path: HoiModule.yml  
---
apiVersion: v1
kind: Service
metadata:
  name: netherlandsbot-core-service
spec:
  type: LoadBalancer
  selector:
    app: netherlandsbot-core
  ports:
  - protocol: TCP
    name: tcp-module
    port: 5555
    targetPort: 5555
