apiVersion: v1
kind: Secret
metadata:
  name: sonarr-iscsi-chap
  namespace: default
type: "kubernetes.io/iscsi-chap"
data:
  node.session.auth.username: "c29uYXJyCg=="
  node.session.auth.password: "WlBIZUJLNDdybjVaRlhyOXkzakMK"
---
#Sonarrs storage directory. iSCSI
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  iscsi:
    targetPortal: 192.168.2.2:3260
    iqn: 'iqn.2021-02.storage.thedutchmc.nl:sonarr'
    lun: 1
    fsType: 'ext4'
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: sonarr-iscsi-chap
  persistentVolumeReclaimPolicy: Retain
---
#Transmissions download directory. NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-sonarr-storage-pv
spec:
  capacity:
    storage: 2000G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-pool/VM/100/transmission/completed
    server: 192.168.1.8
  persistentVolumeReclaimPolicy: Retain
---
#Export Directory for Sonarr. NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvshow-sonarr-storage-pv
spec:
  capacity:
    storage: 10000G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-pool/media/tvshows
    server: 192.168.1.8
  persistentVolumeReclaimPolicy: Retain
---
#Sonarrs config directory
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
spec:
  volumeName: sonarr-config-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
---
#Transmissions download directory
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-sonarr-storage-pvc
spec:
  volumeName: transmission-sonarr-storage-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000G
---
#Sonarrs export directory for TV Shows
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvshow-sonarr-storage-pvc
spec:
  volumeName: tvshow-sonarr-storage-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000G
---
#Deployment. Sonarr container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-deployment
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: 'linuxserver/sonarr:preview'
        ports:
        #Webinterface
        - containerPort: 8989
          name: webint
        volumeMounts:
        #Sonarrs config directory (iSCSI)
        - name: sonarr-config
          mountPath: /config
        #Transmission download directory
        - name: transmission-storage
          mountPath: /data/completed/
        #Final resting place for the downloaded media
        - name: tvshow-storage
          mountPath: /tv
      volumes:
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-config-pvc
      - name: transmission-storage
        persistentVolumeClaim:
          claimName: transmission-sonarr-storage-pvc
      - name: tvshow-storage
        persistentVolumeClaim: 
          claimName: tvshow-sonarr-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
spec:
  selector:
    app: sonarr
  ports:
  #Webinterface
  - protocol: TCP
    name: webint
    port: 8989
    targetPort: 8989
---
#Ingress resource. Picked up by the NGINX ingress controller
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sonarr-ingress
  annotations:
    kubernets.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: 85.144.63.138,192.168.1.0/24
    nginx.ingress.kubernetes.io/proxy-body-size: 150m

spec:
  tls:
  - hosts:
    - sonarr.k8s.thedutchmc.nl
    secretName: thedutchmc-tls
  rules:
  - host: sonarr.k8s.thedutchmc.nl
    http:
      paths:
      - backend:
          serviceName: sonarr-service
          servicePort: 8989
