apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmquery
  namespace: mrfriendly
  labels:
    app: crmquery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmquery
  template:
    metadata:
      labels:
        app: crmquery
    spec:
      containers:
      - name: crmquery
        imagePullPolicy: Always
        image: registry.thedutchmc.nl/mrfriendly-crmquery:latest
        ports:
        - containerPort: 80
          name: web
        env:
        - name: "ESPO_API_KEY"
          valueFrom:
            secretKeyRef:
              name: crmquery
              key: ESPO_API_KEY
        - name: "ESPO_URL"
          valueFrom:
            secretKeyRef:
              name: crmquery
              key: "ESPO_URL"
---
apiVersion: v1
kind: Service
metadata:
  name: crmquery
  namespace: mrfriendly
spec:
  selector:
    app: crmquery
  ports:
  - protocol: TCP
    name: web
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crmquery
  namespace: mrfriendly
  annotations:
    kubernets.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - crmquery.intern.mrfriendly.nl
    secretName: mrfriendly-tls
  rules:
  - host: crmquery.intern.mrfriendly.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crmquery
            port: 
              number: 80
