apiVersion: apps/v1
kind: Deployment
metadata:
  name: espogmailsync
  namespace: mrfriendly
  labels:
    app: espogmailsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: espogmailsync
  template:
    metadata:
      labels:
        app: espogmailsync
    spec:
      containers:
      - name: espogmailsync-api
        image: docker-registry.k8s.array21.dev/espogmailsync-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: api-port
        env:
        - name: "DEBUG"
          value: "true"
        - name: "AUTH_API_TOKEN"
          valueFrom:
            secretKeyRef:
              name: espogmailsync-api
              key: auth_api_token
        - name: "FRONTEND_HOST"
          value: "https://intern.mrfriendly.nl"
        - name: "AUTH_SERVER_HOST"
          value: "https://api.intern.mrfriendly.nl"
        - name: "ESPO_HOST"
          value: "https://espocrm.intern.mrfriendly.nl"
        - name: "ESPO_API_KEY"
          valueFrom:
            secretKeyRef:
              name: espogmailsync-api
              key: espo_api_key
        - name: "ESPO_SECRET_KEY"
          valueFrom:
            secretKeyRef:
              name: espogmailsync-api
              key: espo_api_secret
        - name: "MYSQL_HOST"
          value: "192.168.1.222:3306"
        - name: "MYSQL_DB"
          value: "espogmailsync"
        - name: "MYSQL_USERNAME"
          valueFrom:
            secretKeyRef:
              name: espogmailsync-api
              key: mysql_username
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: espogmailsync-api
              key: mysql_password
      # TODO Frontend container
---
apiVersion: v1
kind: Service
metadata:
  name: espogmailsync
  namespace: mrfriendly
spec:
  selector:
    app: espogmailsync
  ports:
  - protocol: TCP
    name: api
    port: 8080
    targetPort: 8080
  #TODO Frontend ports
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: espogmailsync-api
  namespace: mrfriendly
spec:
  tls:
  - hosts:
    - api.intern.mrfriendly.nl
    secretName: mrfriendly-tls
  rules:
  - host: espogmailsync.api.intern.mrfriendly.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: espogmailsync
            port:
              number: 8080
      
