- hosts: all
  become: yes
  tasks:
   # Apt update
   - name: update APT packages
     apt:
       upgrade: yes
       update_cache: yes
   
   #Qemu Guest agent
   - name: Install QEMU Guest agent
     apt:
       name: qemu-guest-agent
       state: present
       
   #Docker
   - name: install Docker
     apt:
       name: docker.io
       state: present
       update_cache: true

   # Apt transport HTTPS
   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   # Kubernetes APT key
   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   # Kubernetes APT repo
   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   # Kubelet
   - name: install kubelet
     apt:
       name: kubelet
       state: present
       update_cache: true

   # KubeADM
   - name: install kubeadm
     apt:
       name: kubeadm
       state: present
   
   # NFS common
   - name: install nfs-common
     apt:
       name: nfs-common
       state: present
- hosts: master
  become: yes
  tasks:

   # KubeCTL
   - name: install kubectl
     apt:
       name: kubectl
       state: present
       force: yes
   
   # ACL
   - name: Install ACL
     apt:
       name: acl
       state: present
